site_name: TheHive Project Documentation

# mkdocs.yml
site_url: https://thehive-project.github.io/docs
# theme:
#   name: "material"
theme:
  name: material
  palette:
    scheme: default
  logo: 'images/thehive.png'
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    # - navigation.expand
    - navigation.indexes
  palette:
    primary: 'blue'
    accent: blue


plugins:
  - search
  - git-revision-date-localized:
      type: datetime
  - awesome-pages

  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
      # watch:
      #   - thehive4py

extra_css:
  - custom.css

extra:
  social:
    - icon: fontawesome/solid/house
      link: "https://www.thehive-project.org"
    - icon: fontawesome/brands/wordpress
      link: "https://blog.thehive-project.org"
    - icon: fontawesome/brands/twitter
      link: "https://twitter.com/TheHive_Project"
    - icon: fontawesome/brands/github
      link: "https://github.com/TheHive-Project"
    - icon: fontawesome/brands/discord
      link: "https://chat.thehive-project.org"
repo_name: "TheHive-Project/docs"
repo_url: "https://github.com/TheHive-Project/docs"
markdown_extensions:
    - toc:
        permalink: "#"
    - attr_list
    - codehilite
    - admonition
    - pymdownx.critic
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true 
    - pymdownx.details
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
